config/routes.rb
Rails.application.routes.draw do
  resources :species do
    resources :sightings
  end
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :species

end

app/models/species.rb
class Species < ActiveRecord::Base
  validates :name, :presence => true
  has_many :sightings


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def new
    @species = Species.find(params[:species_id])
    @sighting = @species.sightings.new
  end

  def create
    @species = Species.find(params[:species_id])
    @sighting = @species.sightings.new(sighting_params)
    if @sighting.save
      redirect_to species_path(@species)
    else
      render :new
    end
  end

  def destroy
    @species = Species.find(params[:species_id])
    @sighting = Sighting.find(params[:id])
    @sighting.destroy
    redirect_to species_path(@species)
  end

  private
  def sighting_params
    params.require(:sighting).permit(:date, :image, :longitude, :latitude)
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.all
    render :index
  end

  def new
    @species = Species.new
    render :new
  end

  def create
    @species = Species.new(species_params)
    if @species.save
      redirect_to species_index_path
    else
      render :new
    end
  end

  def show
    @species = Species.find(params[:id])
    render :show
  end

  def edit
    @species = Species.find(params[:id])
    render :edit
  end

  def update
    @species = Species.find(params[:id])
    if @species.update(species_params)
      redirect_to species_path(@species)
    else
      render :edit
    end
  end

  def destroy
    @species = Species.find(params[:id])
    @species.destroy
    redirect_to species_index_path
  end

  private
    def species_params
      params.require(:species).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WildlifeTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sightings/_form.html.erb
<%= render "layouts/errors", :object => @sighting %>

<%= form_for [@species, @sighting] do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :longitude %>
  <%= f.text_field :longitude %>

  <%= f.label :latitude %>
  <%= f.text_field :latitude %>

  <%= f.label :image %>
  <%= f.text_field :image %>
  <br><br>
  <%= f.submit %>
<% end %>

app/views/sightings/new.html.erb
<h1>Add Sighting</h1>

<%= render 'form' %>

app/views/species/_form.html.erb
<%= render "layouts/errors", :object => @species %>

<%= form_for @species do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/species/edit.html.erb
<h1>Edit Species</h1>

<%= render "form" %>

app/views/species/index.html.erb
<h1>Species</h1>
<ul>
  <% @species.each do |species| %>
  <li><%= link_to species.name, species_path(species) %></li>
  <% end %>
</ul>

<p>
  <%= link_to "Add Species", new_species_path %>
</p>

app/views/species/new.html.erb
<h1>New Species</h1>

<%= render "form" %>

app/views/species/show.html.erb
<h1><%= @species.name %></h1>

<% if @species.sightings.any? %>
  <h4>Here are the sightings for this species:</h4>

  <ul>
    <% @species.sightings.each do |sighting| %>
      <li>
        <%= sighting.date.strftime("%B %d, %Y") %><br>

        <img src="<%= sighting.image %>" >
        <%= link_to "Delete", species_sighting_path(@species, sighting),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no sightings yet!</p>
<% end %>
<p><%= link_to "Add sighting", new_species_sighting_path(@species) %></p>



<p><%= link_to "Edit", edit_species_path(@species) %></p>

<p><%= link_to "Delete", species_path(@species),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %></p>

<p><%= link_to "Home", species_index_path %></p>